version: "3.9"

services:
  db:
    image: postgres:16
    container_name: kopeika_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kopeika_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    container_name: kopeika_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
      - /app/node_modules
    command: node dist/main.js

volumes:
  pgdata:
  redisdata:
